import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { InferGetStaticPropsType } from "next";

export default function Home(
    props: InferGetStaticPropsType<typeof getStaticProps>
) {
    return (
        <>
            <Head>
                <title>방 | Real Estate Champion</title>
                <meta
                    name="description"
                    content="Generated by create next app using tailwind, eslint, typescript, graphql"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title} data-cy="welcome-greeting">
                    Hello,
                </h1>
            </main>
        </>
    );
}

// This function gets called at build time on server-side.
// It won't be called on client-side.
// SSG (Static Site Generator).
export async function getStaticProps() {
    // Call an external API endpoint to get posts.
    
    return {
        props: {},
    };
}
