import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { getSampleData } from "@/services/sample";
import { InferGetStaticPropsType } from "next";

export default function Home(
    props: InferGetStaticPropsType<typeof getStaticProps>
) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app using tailwind, eslint, typescript, graphql"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title} data-cy="welcome-greeting">
                    Hello,
                </h1>
                <div>
                    <Image
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                    />
                </div>
            </main>
        </>
    );
}

// This function gets called at build time on server-side.
// It won't be called on client-side.
// SSG (Static Site Generator).
export async function getStaticProps() {
    // Call an external API endpoint to get posts.
    
    return {
        props: {},
    };
}
